ALTER TYPE "public"."booking_status" ADD VALUE 'pending_payment' BEFORE 'confirmed';--> statement-breakpoint
ALTER TYPE "public"."booking_status" ADD VALUE 'waitlisted' BEFORE 'cancelled';--> statement-breakpoint
ALTER TYPE "public"."booking_status" ADD VALUE 'payment_failed';--> statement-breakpoint
ALTER TYPE "public"."booking_status" ADD VALUE 'refunded';--> statement-breakpoint
ALTER TYPE "public"."event_status" ADD VALUE 'cancelled';--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "age_min" integer DEFAULT 25 NOT NULL;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "age_max" integer DEFAULT 35 NOT NULL;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "female_capacity" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "male_capacity" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "female_spots_available" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "male_spots_available" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "badge" text;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "image_src" text;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "language" text DEFAULT 'RU/PL' NOT NULL;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "organizer_email" text;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "organizer_first_name" text;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "organizer_image" text;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "organizer_last_name" text;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "organizer_phone" text;--> statement-breakpoint
ALTER TABLE "venues" ADD COLUMN "district" text DEFAULT 'Stare Miasto' NOT NULL;--> statement-breakpoint
ALTER TABLE "venues" ADD COLUMN "latitude" double precision;--> statement-breakpoint
ALTER TABLE "venues" ADD COLUMN "longitude" double precision;--> statement-breakpoint
CREATE INDEX "events_status_idx" ON "events" USING btree ("status");--> statement-breakpoint
INSERT INTO "venues" (
  "id",
  "name",
  "city",
  "district",
  "address",
  "latitude",
  "longitude",
  "map_url",
  "capacity"
) VALUES
  (
    '11111111-1111-4111-8111-111111111111',
    'Restaurant&Bar Stary Spichlerz',
    'Гданьск',
    'Stare Miasto',
    'ul. Chlebnicka 10/11, Gdansk',
    54.3464,
    18.6533,
    'https://www.google.com/maps/search/?api=1&query=Restaurant%26Bar%20Stary%20Spichlerz%2C%20Gdansk',
    32
  ),
  (
    '22222222-2222-4222-8222-222222222222',
    'Loft event space',
    'Гданьск',
    'Wrzeszcz',
    'ul. Slowackiego 23, Gdansk',
    54.381,
    18.6046,
    'https://www.google.com/maps/search/?api=1&query=Loft%20event%20space%2C%20Gdansk',
    36
  ),
  (
    '33333333-3333-4333-8333-333333333333',
    'Garden lounge',
    'Гданьск',
    'Oliwa',
    'ul. Opacka 12, Gdansk',
    54.4104,
    18.5605,
    'https://www.google.com/maps/search/?api=1&query=Garden%20lounge%2C%20Gdansk',
    28
  ),
  (
    '44444444-4444-4444-8444-444444444444',
    'Hotel Almond',
    'Гданьск',
    'Srodmiescie',
    'ul. Torunska 12, Gdansk',
    54.3438,
    18.6483,
    'https://www.google.com/maps/search/?api=1&query=Hotel%20Almond%2C%20Gdansk',
    24
  )
ON CONFLICT ("id") DO UPDATE SET
  "name" = EXCLUDED."name",
  "city" = EXCLUDED."city",
  "district" = EXCLUDED."district",
  "address" = EXCLUDED."address",
  "latitude" = EXCLUDED."latitude",
  "longitude" = EXCLUDED."longitude",
  "map_url" = EXCLUDED."map_url",
  "capacity" = EXCLUDED."capacity",
  "updated_at" = now();--> statement-breakpoint
INSERT INTO "events" (
  "id",
  "venue_id",
  "title",
  "slug",
  "city",
  "starts_at",
  "duration_minutes",
  "conversation_minutes",
  "age_min",
  "age_max",
  "capacity_total",
  "female_capacity",
  "male_capacity",
  "spots_available",
  "female_spots_available",
  "male_spots_available",
  "price_groszy",
  "currency",
  "status",
  "badge",
  "description",
  "image_src",
  "language",
  "organizer_email",
  "organizer_first_name",
  "organizer_last_name",
  "organizer_phone",
  "metadata"
) VALUES
  (
    'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1',
    '11111111-1111-4111-8111-111111111111',
    'RoundDate 25-35',
    'speed-dating-25-35-2031-05-24',
    'Гданьск',
    '2031-05-24 19:00:00+02',
    120,
    10,
    25,
    35,
    20,
    10,
    10,
    12,
    6,
    6,
    12900,
    'PLN',
    'published',
    'Идет набор',
    'Камерный вечер быстрых знакомств в центре города с короткими раундами и понятным темпом.',
    '/assets/home-events/chairs-date.png',
    'RU/PL',
    'hello@rounddate.pl',
    'Anna',
    'Kowalska',
    '+48 500 111 222',
    '{"highlights":["10-минутные раунды","Баланс участников","Контакты после взаимной симпатии"]}'::jsonb
  ),
  (
    'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa2',
    '22222222-2222-4222-8222-222222222222',
    'RoundDate 30-40',
    'speed-dating-30-40-2031-05-31',
    'Гданьск',
    '2031-05-31 19:00:00+02',
    125,
    10,
    30,
    40,
    18,
    9,
    9,
    5,
    2,
    3,
    12900,
    'PLN',
    'published',
    'Почти заполнено',
    'Уютная встреча для тех, кто хочет познакомиться офлайн без долгих переписок.',
    '/assets/home-events/chairs-flowers.png',
    'RU/PL/EN',
    'events@rounddate.pl',
    'Marta',
    'Nowak',
    '+48 500 333 444',
    '{"highlights":["Welcome drink","Маленькая группа","Модератор на месте"]}'::jsonb
  ),
  (
    'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa3',
    '33333333-3333-4333-8333-333333333333',
    'RoundDate 35-45',
    'speed-dating-35-45-2031-06-07',
    'Гданьск',
    '2031-06-07 18:30:00+02',
    110,
    8,
    35,
    45,
    16,
    8,
    8,
    0,
    0,
    0,
    13900,
    'PLN',
    'sold_out',
    'Почти заполнено',
    'Спокойный формат для зрелой аудитории: меньше шума, больше времени на разговор.',
    '/assets/home-events/chairs-coral.png',
    'RU/PL',
    'support@rounddate.pl',
    'Kasia',
    'Zielinska',
    '+48 500 555 666',
    '{"highlights":["Уютная посадка","Возрастная группа 35-45","После события открываем мэтчи"]}'::jsonb
  ),
  (
    'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa4',
    '44444444-4444-4444-8444-444444444444',
    'RoundDate intro',
    'speed-dating-intro-2031-06-14',
    'Гданьск',
    '2031-06-14 20:00:00+02',
    120,
    10,
    25,
    35,
    24,
    12,
    12,
    9,
    4,
    5,
    10900,
    'PLN',
    'published',
    'Новая дата',
    'Легкий формат для первого знакомства с проектом и офлайн-встречами.',
    '/assets/atmosphere/conversation-03.png',
    'RU/PL',
    'hello@rounddate.pl',
    'Anna',
    'Kowalska',
    '+48 500 111 222',
    '{"highlights":["Первое знакомство с форматом","Модератор помогает на месте","Комфортная небольшая группа"]}'::jsonb
  ),
  (
    'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa5',
    '44444444-4444-4444-8444-444444444444',
    'RoundDate finished',
    'speed-dating-finished-2026-04-12',
    'Гданьск',
    '2026-04-12 19:00:00+02',
    120,
    10,
    25,
    35,
    24,
    12,
    12,
    0,
    0,
    0,
    10900,
    'PLN',
    'finished',
    'Завершено',
    'Прошедший вечер быстрых знакомств для проверки истории участника.',
    '/assets/atmosphere/conversation-06.png',
    'RU/PL',
    'hello@rounddate.pl',
    'Anna',
    'Kowalska',
    '+48 500 111 222',
    '{"highlights":["Событие завершено","Результаты доступны","История сохраняется в профиле"]}'::jsonb
  )
ON CONFLICT ("slug") DO UPDATE SET
  "venue_id" = EXCLUDED."venue_id",
  "title" = EXCLUDED."title",
  "city" = EXCLUDED."city",
  "starts_at" = EXCLUDED."starts_at",
  "duration_minutes" = EXCLUDED."duration_minutes",
  "conversation_minutes" = EXCLUDED."conversation_minutes",
  "age_min" = EXCLUDED."age_min",
  "age_max" = EXCLUDED."age_max",
  "capacity_total" = EXCLUDED."capacity_total",
  "female_capacity" = EXCLUDED."female_capacity",
  "male_capacity" = EXCLUDED."male_capacity",
  "spots_available" = EXCLUDED."spots_available",
  "female_spots_available" = EXCLUDED."female_spots_available",
  "male_spots_available" = EXCLUDED."male_spots_available",
  "price_groszy" = EXCLUDED."price_groszy",
  "currency" = EXCLUDED."currency",
  "status" = EXCLUDED."status",
  "badge" = EXCLUDED."badge",
  "description" = EXCLUDED."description",
  "image_src" = EXCLUDED."image_src",
  "language" = EXCLUDED."language",
  "organizer_email" = EXCLUDED."organizer_email",
  "organizer_first_name" = EXCLUDED."organizer_first_name",
  "organizer_last_name" = EXCLUDED."organizer_last_name",
  "organizer_phone" = EXCLUDED."organizer_phone",
  "metadata" = EXCLUDED."metadata",
  "updated_at" = now();
